// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from "../models/models"

export function Greet(arg1: string): Promise<string>;

export function Parse(url: string, length: number): Promise<Array<main.Notice>>;