// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Greet(arg1) {
    return window['go']['main']['App']['Greet'](arg1);
}

export function Parse(arg1, arg2) {
    return window['go']['main']['App']['Parse'](arg1, arg2);
}

export function GetWeather() {
    return window['go']['main']['App']['GetWeather']();
}